project/account/urls.py
from django.urls import path, re_path

from . import views

app_name = "account"

urlpatterns = [
    # User Accounts
    path("signup/", views.signup, name="signup"),
    path("login/", views.signin, name="signin"),
    path("logout/", views.signout, {"next_page": "/"}, name="signout"),
    path("activate_success/", views.activate, name="activate_success"),
    path("profiles/", views.profile_list, name="profile_list"),
    re_path(r"^activate/(?P<activation_key>\w+)/$", views.activate, name="activate"),
    re_path(
        r"^activate/retry/(?P<activation_key>\w+)/$",
        views.activate,
        name="activate_retry",
    ),
    re_path(r"^profile/(?P<username>[-\w]+)$", views.profile, name="profile"),
    re_path(
        r"^profile/(?P<username>[-\w]+)/edit-account$",
        views.account_edit,
        name="account_edit",
    ),
    re_path(
        r"^profile/(?P<username>[-\w]+)/edit-profile$",
        views.profile_edit,
        name="profile_edit",
    ),
    re_path(
        r"^profile/(?P<username>[-\w]+)/edit-settings$",
        views.settings_edit,
        name="user_settings_edit",
    ),
]

project/datacore/urls.py
from django.conf.urls import include
from django.urls import path, re_path
from rest_framework import routers

from . import api, views

app_name = "datacore"

router = routers.DefaultRouter()
router.register(r"data_sources", api.DataSourceViewSet)
router.register(r"references", api.ReferenceViewSet)
router.register(r"linguistics", api.ComponentViewSet)
router.register(r"languages", api.LanguageViewSet)
router.register(r"word_relation_types", api.WordRelationTypeViewSet)
router.register(r"word_relation", api.WordRelationViewSet)
router.register(r"words", api.WordViewSet)
router.register(r"named_entities", api.NamedEntityViewSet)
router.register(r"word_collections", api.WordCollectionViewSet)
router.register(r"concepts", api.ConceptViewSet)
router.register(r"domain_ontologies", api.DomainOntologyViewSet)
router.register(r"definitions", api.DefinitionViewSet)
router.register(r"examples", api.ExampleViewSet)
router.register(r"relations", api.RelationViewSet)
router.register(r"attributes", api.AttributeViewSet)
router.register(r"properties", api.PropertyViewSet)
router.register(r"rules", api.RuleViewSet)
router.register(r"restrictions", api.RestrictionViewSet)
router.register(r"axioms", api.AxiomViewSet)
router.register(r"corpus", api.CorporaViewSet)
router.register(r"phrase_collection", api.PhraseCollectionViewSet)
router.register(r"documents", api.DocumentViewSet)
router.register(r"phrase_relation_types", api.PhraseRelationTypeViewSet)
router.register(r"phrases", api.PhraseViewSet)
router.register(r"templates", api.TemplateViewSet)


urlpatterns = [
    # home
    re_path(r"^$", views.index, name="home"),
    path("search/", views.search, name="search"),
    path("analyze/", views.analyze, name="analyze"),
    # API
    path(r"api/", include((router.urls, "datacore"))),
    # all the pages
    path("corpora/", views.corpora, name="corpora"),
    path("corpora/add/", views.corpora_add, name="corpora_add"),
    re_path(
        r"^corpus/(?P<id>\d+)/documents_add$",
        views.corpus_documents_add,
        name="corpus_documents_add",
    ),
    re_path(
        r"^corpus/(?P<id>\d+)/documents$",
        views.corpus_documents,
        name="corpus_documents",
    ),
    re_path(
        r"^corpus/(?P<id>\d+)/phrase_collections_add$",
        views.corpus_phrase_collections_add,
        name="corpus_phrase_collections_add",
    ),
    re_path(
        r"^corpus/(?P<id>\d+)/phrase_collections$",
        views.corpus_phrase_collections,
        name="corpus_phrase_collections",
    ),
    re_path(r"^corpus/(?P<id>\d+)/edit$", views.corpus_edit, name="corpus_edit"),
    re_path(r"^corpus/(?P<id>\d+)/delete$", views.corpus_delete, name="corpus_delete"),
    re_path(r"^corpus/(?P<id>\d+)/$", views.corpus, name="corpus"),
    path("documents/", views.documents, name="documents"),
    path("documents/add", views.documents_add, name="documents_add"),
    re_path(r"^document/(?P<id>\d+)/edit$", views.document_edit, name="document_edit"),
    re_path(
        r"^document/(?P<id>\d+)/delete$", views.document_delete, name="document_delete"
    ),
    re_path(r"^document/(?P<id>\d+)$", views.document, name="document"),
    path("phrase-collections/", views.phrase_collections, name="phrase_collections"),
    path(
        "phrase-collections/add",
        views.phrase_collections_add,
        name="phrase_collections_add",
    ),
    re_path(
        r"^phrase-collection/(?P<id>\d+)/add_phrase$",
        views.phrase_collection_add_phrase,
        name="phrase_collection_add_phrase",
    ),
    re_path(
        r"^phrase-collection/(?P<id>\d+)/edit$",
        views.phrase_collection_edit,
        name="phrase_collection_edit",
    ),
    re_path(
        r"^phrase-collection/(?P<id>\d+)/delete$",
        views.phrase_collection_delete,
        name="phrase_collection_delete",
    ),
    re_path(
        r"^phrase-collection/(?P<id>\d+)$",
        views.phrase_collection,
        name="phrase_collection",
    ),
    path("phrases/", views.phrases, name="phrases"),
    path("phrases/add", views.phrases_add, name="phrases_add"),
    re_path(r"^phrase/(?P<id>\d+)/edit$", views.phrase_edit, name="phrase_edit"),
    re_path(r"^phrase/(?P<id>\d+)/delete$", views.phrase_delete, name="phrase_delete"),
    re_path(r"^phrase/(?P<id>\d+)$", views.phrase, name="phrase"),
    path("words/", views.words, name="words"),
    path("words/add", views.words_add, name="words_add"),
    re_path(r"^word/(?P<id>\d+)/edit$", views.word_edit, name="word_edit"),
    re_path(r"^word/(?P<id>\d+)/delete$", views.word_delete, name="word_delete"),
    re_path(r"^word/(?P<id>\d+)$", views.word, name="word"),
    path("domain_ontologies/", views.domain_ontologies, name="domain_ontologies"),
    path(
        "domain_ontologies/add",
        views.domain_ontologies_add,
        name="domain_ontologies_add",
    ),
    re_path(
        r"^domain_ontology/(?P<id>\d+)/concept_add$",
        views.domain_ontology_concept_add,
        name="domain_ontology_concept_add",
    ),
    re_path(
        r"^domain_ontology/(?P<id>\d+)/edit$",
        views.domain_ontology_edit,
        name="domain_ontology_edit",
    ),
    re_path(
        r"^domain_ontology/(?P<id>\d+)/delete$",
        views.domain_ontology_delete,
        name="domain_ontology_delete",
    ),
    re_path(
        r"^domain_ontology/(?P<id>\d+)$", views.domain_ontology, name="domain_ontology"
    ),
    path("concepts/", views.concepts, name="concepts"),
    path("concepts/add", views.concepts_add, name="concepts_add"),
    re_path(
        r"^concept/(?P<id>\d+)/synonyms$",
        views.concept_synonyms,
        name="concept_synonyms",
    ),
    re_path(
        r"^concept/(?P<id>\d+)/synonyms_add$",
        views.concept_synonyms_add,
        name="concept_synonyms_add",
    ),
    re_path(
        r"^concept/(?P<id>\d+)/synonym_edit/(?P<rel_id>\d+)$",
        views.concept_synonym_edit,
        name="concept_synonym_edit",
    ),
    re_path(
        r"^concept/(?P<id>\d+)/antonyms$",
        views.concept_antonyms,
        name="concept_antonyms",
    ),
    re_path(
        r"^concept/(?P<id>\d+)/antonyms_add$",
        views.concept_antonyms_add,
        name="concept_antonyms_add",
    ),
    re_path(
        r"^concept/(?P<id>\d+)/antonym_edit/(?P<rel_id>\d+)$",
        views.concept_antonym_edit,
        name="concept_antonym_edit",
    ),
    re_path(
        r"^concept/(?P<id>\d+)/definitions$",
        views.concept_definitions,
        name="concept_definitions",
    ),
    re_path(
        r"^concept/(?P<id>\d+)/definitions_add$",
        views.concept_definitions_add,
        name="concept_definitions_add",
    ),
    re_path(
        r"^concept/(?P<id>\d+)/definition_edit/(?P<rel_id>\d+)$",
        views.concept_definition_edit,
        name="concept_definition_edit",
    ),
    re_path(
        r"^concept/(?P<id>\d+)/examples$",
        views.concept_examples,
        name="concept_examples",
    ),
    re_path(
        r"^concept/(?P<id>\d+)/examples_add$",
        views.concept_examples_add,
        name="concept_examples_add",
    ),
    re_path(
        r"^concept/(?P<id>\d+)/example_edit/(?P<rel_id>\d+)$",
        views.concept_example_edit,
        name="concept_example_edit",
    ),
    re_path(
        r"^concept/(?P<id>\d+)/relationships$",
        views.concept_relationships,
        name="concept_relationships",
    ),
    re_path(
        r"^concept/(?P<id>\d+)/relationships_add$",
        views.concept_relationships_add,
        name="concept_relationships_add",
    ),
    re_path(
        r"^concept/(?P<id>\d+)/visualization$",
        views.concept_visualization,
        name="concept_visualization",
    ),
    re_path(r"^concept/(?P<id>\d+)$", views.concept, name="concept"),
    path("entities/", views.entities, name="entities"),
    path("entities/add", views.entities_add, name="entities_add"),
    re_path(r"^entity/(?P<id>\d+)/edit$", views.entity_edit, name="entity_edit"),
    re_path(r"^entity/(?P<id>\d+)/delete$", views.entity_delete, name="entity_delete"),
    re_path(r"^entity/(?P<id>\d+)$", views.entity, name="entity"),
    path("templates/", views.templates, name="templates"),
    re_path(r"^template/(?P<id>\d+)$", views.template, name="template"),
    path("components/", views.components, name="components"),
    re_path(r"^component/(?P<slug>.+)/$", views.component, name="component"),
    path("languages/", views.languages, name="languages"),
    path("languages/add", views.languages_add, name="languages_add"),
    re_path(r"^language/(?P<id>\d+)/edit$", views.language_edit, name="language_edit"),
    re_path(
        r"^language/(?P<id>\d+)/delete$", views.language_delete, name="language_delete"
    ),
    re_path(r"^language/(?P<id>\d+)/$", views.language, name="language"),
    path("word-relation-types/", views.word_relation_types, name="word_relation_types"),
    path(
        "word-relation-types/add",
        views.word_relation_types_add,
        name="word_relation_types_add",
    ),
    re_path(
        r"^word-relation-type/(?P<id>\d+)/edit$",
        views.word_relation_type_edit,
        name="word_relation_type_edit",
    ),
    re_path(
        r"^word-relation-type/(?P<id>\d+)/delete$",
        views.word_relation_type_delete,
        name="word_relation_type_delete",
    ),
    re_path(
        r"^word-relation-type/(?P<id>\d+)$",
        views.word_relation_type,
        name="word_relation_type",
    ),
    path("word-relations/", views.word_relations, name="word_relations"),
    path("word-relations/add", views.word_relations_add, name="word_relations_add"),
    re_path(
        r"^word-relation/(?P<id>\d+)/edit$",
        views.word_relation_edit,
        name="word_relation_edit",
    ),
    re_path(
        r"^word-relation/(?P<id>\d+)/delete$",
        views.word_relation_delete,
        name="word_relation_delete",
    ),
    re_path(r"^word-relation/(?P<id>\d+)$", views.word_relation, name="word_relation"),

project/datacore/templates/concept-examples.html
{% extends base_template %}
{% load static %}
{% load i18n %}
{% load general_tags %}

{% block title %}{% trans "Concept Examples" %}{% endblock %}

{% block content %}
	<!-- Page Content -->
	{% if request.htmx.target != 'tab-container' %}
		<!-- Modal -->
		<div class="modal fade" id="page-modal" tabindex="-1" aria-labelledby="modal-label" aria-hidden="true">
			<div class="modal-dialog">
				<div id="modal-container" class="modal-content">
				</div>
			</div>
		</div>

		<h1>
			<a hx-indicator="#loading-indicator" hx-target="#main-container" hx-push-url="true" hx-boost="true" href="{% url 'datacore:concept' concept.id %}">{% trans "Concept" %} #{{ id }}</a>
			<span class="badge bg-secondary fs-6 align-middle">{{ concept.pos.title }}</span>
			<div id="loading-indicator" class="htmx-indicator spinner-border" role="status"><span class="visually-hidden">Loading...</span></div>
		</h1>
		{% tabs tab_data tab_active %}
	{% endif %}

	<div id="tab-container">
		<h4>
			Examples
			<a hx-push-url="false" hx-boost="true" hx-target="#modal-container" hx-indicator="#loading-indicator" href="{% url 'datacore:concept_examples_add' concept.id %}" class="btn btn-success btn-sm float-end" data-bs-toggle="modal" data-bs-target="#page-modal"><i class="fa fa-add"></i> Add Example</a>
		</h4>
		{% if concept.examples.all %}
			<div class="row gy-2 pt-3">
				{% for example in concept.examples.all %}
					<div class="col-auto">
						<div class="input-group">
							<span class="input-group-text" id="basic-addon1"><abbr title="{{example.language.get_title}}">{{example.language.alpha3b}}</abbr></span>
							<span class="form-control">{{ example.text }}</span>
							<button class="btn btn-outline-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false"></button>
							<ul class="dropdown-menu">
								<li><a hx-vals='{"force_url_success_redirect": "{% url "datacore:concept" concept.id %}"}' hx-push-url="false" hx-boost="true" hx-indicator="#loading-indicator" hx-target="#modal-container" href="{% url 'datacore:concept_example_edit' concept.id example.id %}" class="dropdown-item" data-bs-toggle="modal" data-bs-target="#page-modal"><i class="fa fa-pen"></i>Edit</a></li>
								<li>
									<form method="post" action="{% url 'datacore:concept_examples' concept.id %}">
										{% csrf_token %}
										<input type="hidden" name="remove-item" value="{{ example.id }}" >
										<button hx-indicator="#loading-indicator" hx-target="#main-container" hx-confirm="Are you sure you?" hx-post="{% url 'datacore:concept_examples' concept.id %}" name="remove-example" class="dropdown-item"><i class="fa fa-trash"></i>Remove</button>
									</form>
								</li>
							</ul>
						</div>
					</div>
				{% endfor %}
			</div>
		{% else %}
			<b>Examples not provided!</b>
		{% endif %}
	</div>
{% endblock %}

project/datacore/templates/concept-relationships.html
{% extends base_template %}
{% load static %}
{% load i18n %}
{% load general_tags %}

{% block title %}{% trans "Concept Relationships" %}{% endblock %}

{% block content %}
	<!-- Page Content -->
	{% if request.htmx.target != 'tab-container' %}
		<!-- Modal -->
		<div class="modal fade" id="page-modal" tabindex="-1" aria-labelledby="modal-label" aria-hidden="true">
			<div class="modal-dialog">
				<div id="modal-container" class="modal-content">
				</div>
			</div>
		</div>

		<h1>
			<a hx-indicator="#loading-indicator" hx-target="#main-container" hx-push-url="true" hx-boost="true" href="{% url 'datacore:concept' concept.id %}">{% trans "Concept" %} #{{ id }}</a>
			<span class="badge bg-secondary fs-6 align-middle">{{ concept.pos.title }}</span>
			<div id="loading-indicator" class="htmx-indicator spinner-border" role="status"><span class="visually-hidden">Loading...</span></div>
		</h1>
		{% tabs tab_data tab_active %}
	{% endif %}

	<div id="tab-container">
		<h4>
			Relationships
			<a hx-push-url="false" hx-boost="true" hx-target="#modal-container" hx-indicator="#loading-indicator" href="{% url 'datacore:concept_relationships_add' concept.id %}" class="btn btn-success btn-sm float-end" data-bs-toggle="modal" data-bs-target="#page-modal"><i class="fa fa-add"></i> Add Relations</a>
		</h4>
		<ul hx-boost="true" class="list-group">
			{% for relation in relations %}
				<li class="list-group-item">
					<a hx-indicator="#loading-indicator" hx-target="#main-container" hx-push-url="true" href="{% url 'datacore:concept' relation.concepts.0 %}">{% get_method_from_list related_concepts relation.concepts.0 "get_title" %}</a>
					{% get_method_from_list related_concept_rels relation.relation_type "title" %}
					<a hx-indicator="#loading-indicator" hx-target="#main-container" hx-push-url="true" href="{% url 'datacore:concept' relation.concepts.1 %}">{% get_method_from_list related_concepts relation.concepts.1 "get_title" %}</a>
					<form class="float-end" method="post">
						{% csrf_token %}
						<input type="hidden" name="relation-id" value="{{relation.id}}">
						<button hx-indicator="#loading-indicator" hx-target="#main-container" hx-confirm="Are you sure you?" hx-post="{% url 'datacore:concept_relationships' concept.id %}" class="btn btn-danger btn-sm float-end" type="submit" value="1" name="remove-relation">Remove</button>
					</form>
				</li>
			{% endfor %}
		</ul>
	</div>
{% endblock %}

project/datacore/templates/concepts.html
{% extends base_template %}
{% load static %}
{% load i18n %}
{% load general_tags %}

{% block title %}{% trans "Concepts" %}{% endblock %}

{% block content %}
	<!-- Modal -->
	<div class="modal fade" id="page-modal" tabindex="-1" aria-labelledby="modal-label" aria-hidden="true">
		<div class="modal-dialog">
			<div id="modal-container" class="modal-content">
			</div>
		</div>
	</div>

	<!-- Page Content -->
	<h1 class="page-header">
		{% trans "Concepts" %}
		<div id="loading-indicator" class="htmx-indicator spinner-border" role="status"><span class="visually-hidden">Loading...</span></div>
		<a hx-indicator="#loading-indicator" hx-push-url="false" hx-boost="true" hx-target="#modal-container" href="{% url 'datacore:concepts_add' %}" class="float-end btn btn-outline-success mx-2 my-2" data-bs-toggle="modal" data-bs-target="#page-modal"><i class="fa fa-add"></i></a>
	</h1>

	{% if concepts|length == 0 %}
		<div class="content">
			No concepts found!
		</div>
	{% else %}
		<div class="row row-margin-bottom">
			<div class="list-group w-100">
				{% for concept in concepts %}
					<a hx-indicator="#loading-indicator" hx-push-url="true" hx-boost="true" hx-target="#main-container" href="{% url 'datacore:concept' concept.id %}" class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
						{{ concept.get_title }}
					</a>
				{% endfor %}
			</div>
		</div>
		{% pagination concepts paginator_range %}
	{% endif %}
{% endblock %}

project/datacore/templates/corpus.html
{% extends base_template %}
{% load static %}
{% load i18n %}
{% load general_tags %}

{% block title %}{% trans "Corpus" %} - {{ corpus.title }}{% endblock %}

{% block content %}
	<!-- Modal -->
	<div class="modal fade" id="page-modal" tabindex="-1" aria-labelledby="modal-label" aria-hidden="true">
		<div class="modal-dialog">
			<div id="modal-container" class="modal-content">
			</div>
		</div>
	</div>

	<!-- Page Content -->
	<h1 class="page-header">
		{{ corpus.title }}
		<div id="loading-indicator" class="htmx-indicator spinner-border" role="status"><span class="visually-hidden">Loading...</span></div>
		<div class="btn-group float-end">
			<a hx-push-url="false" hx-boost="true" hx-indicator="#loading-indicator" hx-target="#modal-container" href="{% url 'datacore:corpus_edit' corpus.id %}" class="btn btn-outline-info" data-bs-toggle="modal" data-bs-target="#page-modal"><i class="fa fa-pen"></i></a>
			<a hx-push-url="false" hx-boost="true" hx-indicator="#loading-indicator" hx-target="#modal-container" href="{% url 'datacore:corpus_delete' corpus.id %}" class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#page-modal"><i class="fa fa-trash-can"></i></a>
		</div>
	</h1>

	{% if corpus.description %}
		<p>{{ corpus.description }}</p>
	{% endif %}
   <hr>

	{% if corpus.data_sources.all|length > 0 %}
		<div class="mb-3 row">
			<label class="col-sm-2 col-form-label">Sources:</label>
			<div class="col-sm-10">
				<ul hx-boost="true" class="list-group list-group-flush">
					{% for data_source in corpus.data_sources.all %}
						<a hx-indicator="#loading-indicator" hx-target="#main-container" hx-push-url="true" href="{% url 'datacore:data_source' data_source.id %}" class="list-group-item">
							{{ data_source.title }}{% if not forloop.last %}, {% endif %}
						</a>
					{% endfor %}
				</ul>
			</div>
		</div>
		<hr>
	{% endif %}

	<ul hx-boost="true" class="list-group">
		<a hx-indicator="#loading-indicator" hx-target="#main-container" hx-push-url="true" href="{% url 'datacore:corpus_documents' corpus.id %}" class="list-group-item d-flex justify-content-between align-items-start">
			<div class="ms-2 me-auto">
				<div class="fw-bold">Documents</div>
				{# TODO: load links to last few edided documents, instead of following#}
				{% if corpus.documents.count == 0 %}No documents found!{% else %}{{ corpus.documents.count }} Corpus Documents Found{% endif %}
			</div>
			<span class="badge bg-primary rounded-pill">{{ corpus.documents.count }}</span>
		</a>
		<a hx-indicator="#loading-indicator" hx-target="#main-container" hx-push-url="true" href="{% url 'datacore:corpus_phrase_collections' corpus.id %}" class="list-group-item d-flex justify-content-between align-items-start">
			<div class="ms-2 me-auto">
				<div class="fw-bold">Phrase Collections</div>
				{% if corpus.phrase_collections.count == 0 %}No Phrase Collections found!{% else %}{{ corpus.phrase_collections.count }} Corpus Phrase Collections.{% endif %}
			</div>
			<span class="badge bg-primary rounded-pill">{{ corpus.phrase_collections.count }}</span>
		</a>
	</ul>
{% endblock %}

project/datacore/templates/index.html
{% extends base_template %}
{% load static %}
{% load i18n %}

{% block title %}{% trans "Home" %}{% endblock %}

{% block content %}
	<div class="row">
		<div class="col">
			<h1>Statistics</h1>
			<table class="table table-dark">
				<tbody>
					<tr>
						<td>Concepts</td>
						<td>{{ concepts }}</td>
					</tr>
					<tr>
						<td>Words</td>
						<td>{{ words }}</td>
					</tr>
					<tr>
						<td>Relationships</td>
						<td>{{ relationships }}</td>
					</tr>
					<tr>
						<td>Examples</td>
						<td>{{ examples }}</td>
					</tr>					<tr>
						<td>Phrases</td>
						<td>{{ phrases }}</td>
					</tr>
					<tr>
						<td>Documents</td>
						<td>{{ documents }}</td>
					</tr>
				</tbody>
			</table>
		</div>
		<div class="col col-lg-8">
			<h1>Search</h1>
			<form id="search" action="{% url 'datacore:search' %}" method="get" accept-charset="utf-8">
				<div class="input-group mb-3">
					<input type="text" name="query" class="form-control" placeholder="Enter a word" aria-label="Enter a word" aria-describedby="button-addon1">
					<div class="input-group-btn">
						<button class="btn btn-outline-secondary" type="submit" id="button-addon1">Search</button>
					</div>
				</div>
			</form>
			<h1>Analyze Sentences</h1>
			<form id="analyze" action="{% url 'datacore:analyze' %}" method="post" accept-charset="utf-8">
				{% csrf_token %}
				<div class="input-group mb-3">
					<textarea rows="4" cols="50" name="analyze_phrase_input" class="form-control" placeholder="Sentence" aria-label="Sentence" aria-describedby="button-addon2"></textarea>
					<div class="input-group-btn">
						<button class="btn btn-outline-secondary" type="submit" value="Analyze" name="analyze_phrase" id="button-addon2">Analyse</button>
					</div>
				</div>
			</form>
		</div>
	</div>
{% endblock %}

project/datacore/templates/phrase-collection.html
{% extends base_template %}
{% load static %}
{% load i18n %}

{% block title %}{% trans "Phrase Collection" %}{% endblock %}

{% block content %}
	<!-- Modal -->
	<div class="modal fade" id="page-modal" tabindex="-1" aria-labelledby="modal-label" aria-hidden="true">
		<div class="modal-dialog">
			<div id="modal-container" class="modal-content">
			</div>
		</div>
	</div>

	<!-- Page Content -->
	<h1 class="page-header">
		{{ phrase_collection.title }}
		<div id="loading-indicator" class="htmx-indicator spinner-border" role="status"><span class="visually-hidden">Loading...</span></div>
		<div class="btn-group float-end">
			<a hx-push-url="false" hx-boost="true" hx-indicator="#loading-indicator" hx-target="#modal-container" href="{% url 'datacore:phrase_collection_add_phrase' phrase_collection.id %}" class="btn btn-outline-success" data-bs-toggle="modal" data-bs-target="#page-modal"><i class="fa fa-add"></i></a>
			<a hx-push-url="false" hx-boost="true" hx-indicator="#loading-indicator" hx-target="#modal-container" href="{% url 'datacore:phrase_collection_edit' phrase_collection.id %}" class="btn btn-outline-info" data-bs-toggle="modal" data-bs-target="#page-modal"><i class="fa fa-pen"></i></a>
			<a hx-push-url="false" hx-boost="true" hx-indicator="#loading-indicator" hx-target="#modal-container" href="{% url 'datacore:phrase_collection_delete' phrase_collection.id %}" class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#page-modal"><i class="fa fa-trash-can"></i></a>
		</div>
	</h1>

	{% if phrase_collection.description %}<h4>Description: {{ phrase_collection.description }}</h4>{% endif %}
	{% if phrase_collection.data_source.title %}<h5>Source: {{ phrase_collection.data_source.title }}</h5>{% endif %}
	<hr>
	{% if phrase_collection.phrases.all|length == 0 %}
		<div class="content">
			No phrase found!
		</div>
	{% else %}
		<div class="row row-margin-bottom">
			<div hx-boost="true" class="list-group w-100">
				{% for phrase in phrase_collection.phrases.all %}
					<li class="list-group-item list-group-item-action d-flex justify-content-between align-items-center p-0">
						<a hx-indicator="#loading-indicator" hx-target="#main-container" hx-push-url="true" href="{% url 'datacore:phrase' phrase.id %}" class="flex-grow-1 p-2">{{ phrase.text }}</a>
						<div class="dropdown">
							<button class="btn btn-danger dropdown-toggle btn-sm m-1" type="button" data-bs-toggle="dropdown" aria-expanded="false">
								<i class="fa fa-trash"></i>
								<span id="phrase-loading-{{ phrase.id }}" class="htmx-indicator hidden-loading spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
							</button>
							<ul class="dropdown-menu">
								<form action="{% url 'datacore:phrase_collection' phrase_collection.id %}" method="post">
									{% csrf_token %}
									<input type="hidden" name="phrase-id" value="{{ phrase.id }}">
									<li><button hx-indicator="#phrase-loading-{{ phrase.id }}" hx-target="#main-container" hx-confirm="Are you sure you?" hx-post="{% url 'datacore:phrase_collection' phrase_collection.id %}" class="dropdown-item" type="submit" name="remove-phrase" value="1">Remove from collection</button></li>
									<li><button hx-indicator="#phrase-loading-{{ phrase.id }}" hx-target="#main-container" hx-confirm="Are you sure you?" hx-post="{% url 'datacore:phrase_collection' phrase_collection.id %}" class="dropdown-item" type="submit" name="delete-phrase" value="1">Delete Phrase</button></li>
								</form>
							</ul>
						</div>
					</li>
				{% endfor %}
			</div>
		</div>
	{% endif %}
{% endblock %}