project/account/urls.py
from django.urls import path, re_path

from . import views

app_name = "account"

urlpatterns = [
    # User Accounts
    path("signup/", views.signup, name="signup"),
    path("login/", views.signin, name="signin"),
    path("logout/", views.signout, {"next_page": "/"}, name="signout"),
    path("activate_success/", views.activate, name="activate_success"),
    path("profiles/", views.profile_list, name="profile_list"),
    re_path(r"^activate/(?P<activation_key>\w+)/$", views.activate, name="activate"),
    re_path(
        r"^activate/retry/(?P<activation_key>\w+)/$",
        views.activate,
        name="activate_retry",
    ),
    re_path(r"^profile/(?P<username>[-\w]+)$", views.profile, name="profile"),
    re_path(
        r"^profile/(?P<username>[-\w]+)/edit-account$",
        views.account_edit,
        name="account_edit",
    ),
    re_path(
        r"^profile/(?P<username>[-\w]+)/edit-profile$",
        views.profile_edit,
        name="profile_edit",
    ),
    re_path(
        r"^profile/(?P<username>[-\w]+)/edit-settings$",
        views.settings_edit,
        name="user_settings_edit",
    ),
]

project/datacore/urls.py
from django.conf.urls import include
from django.urls import path, re_path
from rest_framework import routers

from . import api, views

app_name = "datacore"

router = routers.DefaultRouter()
router.register(r"data_sources", api.DataSourceViewSet)
router.register(r"references", api.ReferenceViewSet)
router.register(r"linguistics", api.ComponentViewSet)
router.register(r"languages", api.LanguageViewSet)
router.register(r"word_relation_types", api.WordRelationTypeViewSet)
router.register(r"word_relation", api.WordRelationViewSet)
router.register(r"words", api.WordViewSet)
router.register(r"named_entities", api.NamedEntityViewSet)
router.register(r"word_collections", api.WordCollectionViewSet)
router.register(r"concepts", api.ConceptViewSet)
router.register(r"domain_ontologies", api.DomainOntologyViewSet)
router.register(r"definitions", api.DefinitionViewSet)
router.register(r"examples", api.ExampleViewSet)
router.register(r"relations", api.RelationViewSet)
router.register(r"attributes", api.AttributeViewSet)
router.register(r"properties", api.PropertyViewSet)
router.register(r"rules", api.RuleViewSet)
router.register(r"restrictions", api.RestrictionViewSet)
router.register(r"axioms", api.AxiomViewSet)
router.register(r"corpus", api.CorporaViewSet)
router.register(r"phrase_collection", api.PhraseCollectionViewSet)
router.register(r"documents", api.DocumentViewSet)
router.register(r"phrase_relation_types", api.PhraseRelationTypeViewSet)
router.register(r"phrases", api.PhraseViewSet)
router.register(r"templates", api.TemplateViewSet)


urlpatterns = [
    # home
    re_path(r"^$", views.index, name="home"),
    path("search/", views.search, name="search"),
    path("analyze/", views.analyze, name="analyze"),
    # API
    path(r"api/", include((router.urls, "datacore"))),
    # all the pages
    path("corpora/", views.corpora, name="corpora"),
    path("corpora/add/", views.corpora_add, name="corpora_add"),
    re_path(
        r"^corpus/(?P<id>\d+)/documents_add$",
        views.corpus_documents_add,
        name="corpus_documents_add",
    ),
    re_path(
        r"^corpus/(?P<id>\d+)/documents$",
        views.corpus_documents,
        name="corpus_documents",
    ),
    re_path(
        r"^corpus/(?P<id>\d+)/phrase_collections_add$",
        views.corpus_phrase_collections_add,
        name="corpus_phrase_collections_add",
    ),
    re_path(
        r"^corpus/(?P<id>\d+)/phrase_collections$",
        views.corpus_phrase_collections,
        name="corpus_phrase_collections",
    ),
    re_path(r"^corpus/(?P<id>\d+)/edit$", views.corpus_edit, name="corpus_edit"),
    re_path(r"^corpus/(?P<id>\d+)/delete$", views.corpus_delete, name="corpus_delete"),
    re_path(r"^corpus/(?P<id>\d+)/$", views.corpus, name="corpus"),
    path("documents/", views.documents, name="documents"),
    path("documents/add", views.documents_add, name="documents_add"),
    re_path(r"^document/(?P<id>\d+)/edit$", views.document_edit, name="document_edit"),
    re_path(
        r"^document/(?P<id>\d+)/delete$", views.document_delete, name="document_delete"
    ),
    re_path(r"^document/(?P<id>\d+)$", views.document, name="document"),
    path("phrase-collections/", views.phrase_collections, name="phrase_collections"),
    path(
        "phrase-collections/add",
        views.phrase_collections_add,
        name="phrase_collections_add",
    ),
    re_path(
        r"^phrase-collection/(?P<id>\d+)/add_phrase$",
        views.phrase_collection_add_phrase,
        name="phrase_collection_add_phrase",
    ),
    re_path(
        r"^phrase-collection/(?P<id>\d+)/edit$",
        views.phrase_collection_edit,
        name="phrase_collection_edit",
    ),
    re_path(
        r"^phrase-collection/(?P<id>\d+)/delete$",
        views.phrase_collection_delete,
        name="phrase_collection_delete",
    ),
    re_path(
        r"^phrase-collection/(?P<id>\d+)$",
        views.phrase_collection,
        name="phrase_collection",
    ),
    path("phrases/", views.phrases, name="phrases"),
    path("phrases/add", views.phrases_add, name="phrases_add"),
    re_path(r"^phrase/(?P<id>\d+)/edit$", views.phrase_edit, name="phrase_edit"),
    re_path(r"^phrase/(?P<id>\d+)/delete$", views.phrase_delete, name="phrase_delete"),
    re_path(r"^phrase/(?P<id>\d+)$", views.phrase, name="phrase"),
    path("words/", views.words, name="words"),
    path("words/add", views.words_add, name="words_add"),
    re_path(r"^word/(?P<id>\d+)/edit$", views.word_edit, name="word_edit"),
    re_path(r"^word/(?P<id>\d+)/delete$", views.word_delete, name="word_delete"),
    re_path(r"^word/(?P<id>\d+)$", views.word, name="word"),
    path("domain_ontologies/", views.domain_ontologies, name="domain_ontologies"),
    path(
        "domain_ontologies/add",
        views.domain_ontologies_add,
        name="domain_ontologies_add",
    ),
    re_path(
        r"^domain_ontology/(?P<id>\d+)/concept_add$",
        views.domain_ontology_concept_add,
        name="domain_ontology_concept_add",
    ),
    re_path(
        r"^domain_ontology/(?P<id>\d+)/edit$",
        views.domain_ontology_edit,
        name="domain_ontology_edit",
    ),
    re_path(
        r"^domain_ontology/(?P<id>\d+)/delete$",
        views.domain_ontology_delete,
        name="domain_ontology_delete",
    ),
    re_path(
        r"^domain_ontology/(?P<id>\d+)$", views.domain_ontology, name="domain_ontology"
    ),
    path("concepts/", views.concepts, name="concepts"),
    path("concepts/add", views.concepts_add, name="concepts_add"),
    re_path(
        r"^concept/(?P<id>\d+)/synonyms$",
        views.concept_synonyms,
        name="concept_synonyms",
    ),
    re_path(
        r"^concept/(?P<id>\d+)/synonyms_add$",
        views.concept_synonyms_add,
        name="concept_synonyms_add",
    ),
    re_path(
        r"^concept/(?P<id>\d+)/synonym_edit/(?P<rel_id>\d+)$",
        views.concept_synonym_edit,
        name="concept_synonym_edit",
    ),
    re_path(
        r"^concept/(?P<id>\d+)/antonyms$",
        views.concept_antonyms,
        name="concept_antonyms",
    ),
    re_path(
        r"^concept/(?P<id>\d+)/antonyms_add$",
        views.concept_antonyms_add,
        name="concept_antonyms_add",
    ),
    re_path(
        r"^concept/(?P<id>\d+)/antonym_edit/(?P<rel_id>\d+)$",
        views.concept_antonym_edit,
        name="concept_antonym_edit",
    ),
    re_path(
        r"^concept/(?P<id>\d+)/definitions$",
        views.concept_definitions,
        name="concept_definitions",
    ),
    re_path(
        r"^concept/(?P<id>\d+)/definitions_add$",
        views.concept_definitions_add,
        name="concept_definitions_add",
    ),
    re_path(
        r"^concept/(?P<id>\d+)/definition_edit/(?P<rel_id>\d+)$",
        views.concept_definition_edit,
        name="concept_definition_edit",
    ),
    re_path(
        r"^concept/(?P<id>\d+)/examples$",
        views.concept_examples,
        name="concept_examples",
    ),
    re_path(
        r"^concept/(?P<id>\d+)/examples_add$",
        views.concept_examples_add,
        name="concept_examples_add",
    ),
    re_path(
        r"^concept/(?P<id>\d+)/example_edit/(?P<rel_id>\d+)$",
        views.concept_example_edit,
        name="concept_example_edit",
    ),
    re_path(
        r"^concept/(?P<id>\d+)/relationships$",
        views.concept_relationships,
        name="concept_relationships",
    ),
    re_path(
        r"^concept/(?P<id>\d+)/relationships_add$",
        views.concept_relationships_add,
        name="concept_relationships_add",
    ),
    re_path(
        r"^concept/(?P<id>\d+)/visualization$",
        views.concept_visualization,
        name="concept_visualization",
    ),
    re_path(r"^concept/(?P<id>\d+)$", views.concept, name="concept"),
    path("entities/", views.entities, name="entities"),
    path("entities/add", views.entities_add, name="entities_add"),
    re_path(r"^entity/(?P<id>\d+)/edit$", views.entity_edit, name="entity_edit"),
    re_path(r"^entity/(?P<id>\d+)/delete$", views.entity_delete, name="entity_delete"),
    re_path(r"^entity/(?P<id>\d+)$", views.entity, name="entity"),
    path("templates/", views.templates, name="templates"),
    re_path(r"^template/(?P<id>\d+)$", views.template, name="template"),
    path("components/", views.components, name="components"),
    re_path(r"^component/(?P<slug>.+)/$", views.component, name="component"),
    path("languages/", views.languages, name="languages"),
    path("languages/add", views.languages_add, name="languages_add"),
    re_path(r"^language/(?P<id>\d+)/edit$", views.language_edit, name="language_edit"),
    re_path(
        r"^language/(?P<id>\d+)/delete$", views.language_delete, name="language_delete"
    ),
    re_path(r"^language/(?P<id>\d+)/$", views.language, name="language"),
    path("word-relation-types/", views.word_relation_types, name="word_relation_types"),
    path(
        "word-relation-types/add",
        views.word_relation_types_add,
        name="word_relation_types_add",
    ),
    re_path(
        r"^word-relation-type/(?P<id>\d+)/edit$",
        views.word_relation_type_edit,
        name="word_relation_type_edit",
    ),
    re_path(
        r"^word-relation-type/(?P<id>\d+)/delete$",
        views.word_relation_type_delete,
        name="word_relation_type_delete",
    ),
    re_path(
        r"^word-relation-type/(?P<id>\d+)$",
        views.word_relation_type,
        name="word_relation_type",
    ),
    path("word-relations/", views.word_relations, name="word_relations"),
    path("word-relations/add", views.word_relations_add, name="word_relations_add"),
    re_path(
        r"^word-relation/(?P<id>\d+)/edit$",
        views.word_relation_edit,
        name="word_relation_edit",
    ),
    re_path(
        r"^word-relation/(?P<id>\d+)/delete$",
        views.word_relation_delete,
        name="word_relation_delete",
    ),
    re_path(r"^word-relation/(?P<id>\d+)$", views.word_relation, name="word_relation"),

project/project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("datacore.urls", namespace="datacore")),
    path("account/", include("account.urls", namespace="account")),
    path("admin/", admin.site.urls, name="admin"),
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
]
urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

project/project/templates/base-clean-header.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>{% block title %}SignUp & SignIn{% endblock %}</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="apple-mobile-web-app-capable" content="yes">
		<meta name="description" content="">
		<meta name="author" content="">

		<link href="http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,400,600" rel="stylesheet">

		<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
		<link href="{% static 'css/style.css' %}" rel="stylesheet">
		<link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">

		<!--[if lt IE 9]>
		<script type="text/javascript" src="{% static '/js/html5shiv.js' %}"></script>
		<![endif]-->

		<!-- Fav and touch icons -->
		<link rel="shortcut icon" href="{% static 'image/favicon.ico'%}">


		{% block header %}
		{% endblock %}
	</head>
	<body>

		<!-- Body Content -->
		{% block content %}
		{% endblock %}

		<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/main.js' %}"></script>
		{% block footer %}
		{% endblock %}
	</body>
</html>

project/project/templates/base.html
{% load static %}
{% load thumbnail %}


<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>{% block title %}ElevateNLP{% endblock %}</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="apple-mobile-web-app-capable" content="yes">
		<meta name="description" content="">
		<meta name="author" content="">

		<!--
		<link href="http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,400,600" rel="stylesheet">
		-->

		<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
		<link href="{% static 'css/fontawesome.min.css' %}" rel="stylesheet">
		<link href="{% static 'css/style.css' %}" rel="stylesheet">

		<script type="text/javascript" src="{% static 'js/bootstrap.bundle.min.js' %}" defer></script>
		<script type="text/javascript" src="{% static 'js/main.js' %}" defer></script>
		<script type="text/javascript" src="{% static 'js/htmx.min.js' %}" defer></script>
  		<meta name="htmx-config" content='{"refreshOnHistoryMiss":"true"}'>

		<!-- Fav and touch icons -->
		<link rel="shortcut icon" href="{% static 'image/favicon.ico'%}">

		{% block header %}
		{% endblock %}
	</head>
	<body>
		<!-- Navigation -->
		{% include 'navbar.html' %}


		<!-- Body Content -->
		<main class="container" id="main-container">
			{% block content %}
			{% endblock %}
		</main>


		<!-- Footer -->
		<footer class="footer mt-auto py-3 bg-light">
			<div class="container">
				<span class="text-center text-muted">&copy; 2019 <a href="http://TheRational.ist/">Tohid</a>.</span>
			</div>
		</footer>

		{% block footer %}
		{% endblock %}
	</body>
</html>

project/project/templates/modal-body.html
{% extends base_template %}
{% load i18n %}
{% load widget_tweaks %}

{# don't change page title for loading modals, because it remains when modal is closed #}
{% block title %}{% if not request.htmx %}{{ title }}{% endif %}{% endblock %}

{% block content %}

<form action="{{ url }}" method="post">
	{% csrf_token %}

	{% if request.GET.force_url_success_redirect %}
		<input type="hidden" name="force_url_success_redirect" value="{{ request.GET.force_url_success_redirect }}">
	{% endif %}

	<div class="modal-header">
		<h1 class="modal-title fs-5" id="modal-label">{{ title }}</h1>
		{% if base_template != 'base.html' %}<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>{% endif %}
	</div>
	<div class="modal-body">
		{% include 'modal-form.html' %}
	</div>
	<div class="modal-footer gap-2">
		<a href="{% if back_url %} {{ back_url }} {% else %} {{ item.get_absolute_url }} {% endif %}" class="btn btn-secondary" {% if base_template != 'base.html' %} data-bs-dismiss="modal"{% endif %}>Back</a>
		<button hx-indicator="#loading-indicator" hx-post="{{ url }}" hx-target="#main-container" hx-push-url="true" type="submit" class="btn btn-primary" name="form-action" value="1" force-refresh="true">{% if action_title %}{{ action_title }}{% else %}{% trans "Save" %}{% endif %}</button>
	</div>
</form>
{% endblock %}

project/project/templates/modal-delete.html
{% extends base_template %}
{% load i18n %}
{% load widget_tweaks %}
{# don't change page title for loading modals, because it remains when modal is closed #}
{% block title %}{% if not request.htmx %}{% if title %} {{ title }} {% else %} {% trans "Alert" %} {% endif %}{% endif %}{% endblock %}

{% block content %}
<form action="{{ url }}" method="delete">
	{% csrf_token %}
	<div class="modal-header">
		<h1 class="modal-title fs-5" id="modal-label">{% if title %} {{ title }} {% else %} {% trans "Alert" %} {% endif %}</h1>
		{% if base_template != 'base.html' %}<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>{% endif %}
	</div>
	<div class="modal-body">
		<p>{% if message %} {{ message }} {% else %} {% trans "Are You Sure?" %} {% endif %}</p>
		{% if item %}<p>{% trans "Object:" %} <a href="{{ item.get_absolute_url }}">{{ item }}</a></p>{% endif %}

	</div>
	<div class="modal-footer gap-2">
		<a href="{% if back_url %} {{ back_url }} {% else %} {{ item.get_absolute_url }} {% endif %}" class="btn btn-secondary" {% if base_template != 'base.html' %} data-bs-dismiss="modal"{% endif %}>Back</a>
		<button hx-push-url="true" hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}' hx-indicator="#loading-indicator" hx-delete="{{ url }}" hx-target="#main-container" type="submit" name="delete" value="1" class="btn btn-danger">{% trans "Delete" %}</button>
	</div>
</form>
{% endblock %}

project/project/templates/modal-item-search.html
{% load i18n %}
{% load widget_tweaks %}
{% load general_tags %}

{% block content %}
	{% if search_items %}
		<div class="content search">
			<ul class="list-group overflow-auto">
				{% for search_item in search_items %}
					<li class="list-group-item">
						{{search_item}}
						<form class="float-end" method="post">
							{% csrf_token %}
							<input type="hidden" name="relation-type" value="{{ relation }}" >
							{# Search if item is already added or not #}
							{% in_relation item relation search_item as added %}
							{% if added %}
								<button hx-indicator="closest button" hx-target="closest li" hx-swap="outerHTML swap:1s" hx-post="{{ url }}" name="remove-relation-item" value="{{ search_item.id }}" type="submit" class="btn btn-danger btn-sm" force-refresh="true">
									{% trans "Remove" %}
									<div class="htmx-indicator hidden-loading spinner-border spinner-border-sm" role="status"></div>
								</button>
							{% else %}
								<button hx-indicator="closest button" hx-target="closest li" hx-swap="outerHTML swap:1s" hx-post="{{ url }}" name="add-relation-item" value="{{ search_item.id }}" type="submit" class="btn btn-success btn-sm" force-refresh="true">
									{% trans "Add" %}
									<div class="htmx-indicator hidden-loading spinner-border spinner-border-sm" role="status"></div>
								</button>
							{% endif %}
							<input type="hidden" name="item-id" value="{{ search_item.id }}">
						</form>
					</li>
				{% endfor %}
			</ul>
		</div>
	{% endif %}
{% endblock %}

project/project/templates/navbar.html
{% load account_tags %}
{% load thumbnail %}
{% load static %}

<nav class="navbar navbar-expand-md navbar-dark bg-dark">
	<div class="container-fluid">
		<a hx-swap="innerHTML show:window:top" hx-target="#main-container" hx-push-url="true" hx-boost="true" hx-indicator="#navbar-indicator" class="navbar-brand" href="{% url 'datacore:home' %}">{% block title %}ElevateNLP{% endblock %}</a>
		<div id="navbar-indicator" class="htmx-indicator spinner-border spinner-border-sm text-light" role="status"><span class="visually-hidden">Loading...</span></div>
		<button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation"><i class="fa fa-bars" aria-hidden="true"></i></button>
		<div id="navbar" class="collapse navbar-collapse">
			<ul hx-swap="innerHTML show:window:top" hx-target="#main-container" hx-push-url="true" hx-boost="true" hx-indicator="#navbar-indicator" class="navbar-nav me-auto mb-2 mb-lg-0">
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Data Collections</a>
					<ul class="dropdown-menu" aria-labelledby="navbarDropdown">
						<li><h6 class="dropdown-header">Text Data</h6></li>
						<li><a class="dropdown-item" href="{% url 'datacore:corpora' %}"><i class="fa fa-book"></i> Corpora</a></li>
						<li><a class="dropdown-item" href="{% url 'datacore:documents' %}"><i class="fa fa-file-lines"></i>Documents</a></li>
						<li><a class="dropdown-item" href="{% url 'datacore:phrase_collections' %}"><i class="fa fa-rectangle-list"></i>Phrase Collections</a></li>
						<li><a class="dropdown-item" href="{% url 'datacore:phrases' %}"><i class="fa fa-quote-left"></i>Phrases</a></li>
						<li><a class="dropdown-item" href="{% url 'datacore:words' %}"><i class="fa fa-spell-check"></i>Words</a></li>
						<li><hr class="dropdown-divider"></li>
						<li><h6 class="dropdown-header">Semantic Data</h6></li>
						<li><a class="dropdown-item" href="{% url 'datacore:domain_ontologies' %}"><i class="fa fa-coins"></i>Domain Ontologies</a></li>
						<li><a class="dropdown-item" href="{% url 'datacore:concepts' %}"><i class="fa fa-database"></i>Concepts</a></li>
						<li><h6 class="dropdown-header">Named Entities</h6></li>
						<li><a class="dropdown-item" href="{% url 'datacore:entities' %}"><i class="fa fa-coins"></i>Named Entities</a></li>
					</ul>
				</li>
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false"> Linguistic Data </a>
					<ul class="dropdown-menu" aria-labelledby="navbarDropdown">
						<li><h6 class="dropdown-header">Linguistics</h6></li>
						<li><a class="dropdown-item" href="{% url 'datacore:components' %}"><i class="fa fa-seedling"></i>Linguistic components</a></li>
						<li><a class="dropdown-item" href="{% url 'datacore:languages' %}"><i class="fa fa-language"></i>Languages</a></li>
						<li><hr class="dropdown-divider"></li>
						<li><h6 class="dropdown-header">Word Morphologies</h6></li>
						<li><a class="dropdown-item" href="{% url 'datacore:word_relation_types' %}">Lexical Relationship types</a></li>
						<li><a class="dropdown-item" href="{% url 'datacore:word_relations' %}">Relations and Morphologies</a></li>
						<li><hr class="dropdown-divider"></li>
						<li><h6 class="dropdown-header">Word Lists</h6></li>
						<li><a class="dropdown-item" href="{% url 'datacore:word_lists' %}">Word Lists</a></li>
						<li><hr class="dropdown-divider"></li>
						<li><h6 class="dropdown-header">Analysis Data</h6></li>
						<li><a class="dropdown-item" href="{% url 'datacore:templates' %}"><i class="fa fa-map"></i> Templates </a></li>
					</ul>
				</li>
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Data Management</a>
					<ul class="dropdown-menu" aria-labelledby="navbarDropdown">
						<li><h6 class="dropdown-header">DataSets</h6></li>
						<li><a class="dropdown-item" href="{% url 'datacore:data_sources' %}">Data Sources</a></li>
						<li><hr class="dropdown-divider"></li>
						<li><h6 class="dropdown-header">Data Export</h6></li>
						<li><a class="dropdown-item" href="{% url 'datacore:lexical_data' %}">Lexical Data</a></li>
						<li><a class="dropdown-item" href="{% url 'datacore:textual_data' %}">Textual Data</a></li>
						<li><a class="dropdown-item" href="{% url 'datacore:ontological_data' %}">Ontology Data</a></li>
					</ul>
				</li>
			</ul>

				{% if request.user.is_authenticated %}
					<ul class="navbar-nav">
						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">
								<i class="fa fa-user"></i>
								{% if request.user.get_full_name %}{{ request.user.get_full_name }}{% else %}{{ request.user.username }}{% endif %}
							</a>
							<ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
								<div class="nav-user-avatar-username-container">
									{% logged_in_user_avatar 128 as avatar %}
									{% if avatar %}
										<img src="{{ avatar }}" class="rounded-circle mx-auto d-flex nav-avatar">
									{% endif %}
									<h5 class="dropdown-item nav-avatar-username">@{{ request.user.username }}</h5>
								</div>
								{% if request.user.is_superuser %}
									<div class="dropdown-divider" role="separator"></div>
									<a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a>
								{%  endif %}
								<div class="dropdown-divider" role="separator"></div>
								<a hx-swap="innerHTML show:window:top" hx-target="#main-container" hx-push-url="true" hx-boost="true" hx-indicator="#navbar-indicator" class="dropdown-item" href="{% url 'account:profile' user %}">Profile</a>
								<a hx-swap="innerHTML show:window:top" hx-target="#main-container" hx-push-url="true" hx-boost="true" hx-indicator="#navbar-indicator" class="dropdown-item" href="{% url 'account:user_settings_edit' user %}">Settings</a>
								<a class="dropdown-item" href="{% url 'account:signout' %}">Logout</a>
							</ul>
						</li>
					</ul>
				{% else %}
					<ul hx-target="#user-modal-container" hx-push-url="false" hx-boost="true" hx-indicator="#navbar-indicator" class="navbar-nav">
						<li class="dropdown"><a class="nav-link" href="{% url 'account:signin' %}" data-bs-toggle="modal" data-bs-target="#user-modal"><i class="fa fa-sign-in"></i> Login</a></li>
						<li class="dropdown"><a class="nav-link" href="{% url 'account:signup' %}" data-bs-toggle="modal" data-bs-target="#user-modal"><i class="fa fa-user-plus"></i> Sign Up</a></li>
					</ul>
				{% endif %}

		</div>
	</div>
</nav>

{% if not request.user.is_authenticated %}
	<!-- User Modal - for login and signup -->
	<div class="modal fade" id="user-modal" tabindex="-1" aria-labelledby="modal-label" aria-hidden="true">
		<div class="modal-dialog">
			<div id="user-modal-container" class="modal-content">
			</div>
		</div>
	</div>
{% endif %}

project/project/templates/partial.html
<title hx-swap-oob="innerHTML:title">{% block title %}{% endblock %}</title>

{% block header %}{% endblock %}
{% block content %}{% endblock %}