project/account/urls.py
from django.urls import path, re_path

from . import views

app_name = "account"

urlpatterns = [
    # User Accounts
    path("signup/", views.signup, name="signup"),
    path("login/", views.signin, name="signin"),
    path("logout/", views.signout, {"next_page": "/"}, name="signout"),
    path("activate_success/", views.activate, name="activate_success"),
    path("profiles/", views.profile_list, name="profile_list"),
    re_path(r"^activate/(?P<activation_key>\w+)/$", views.activate, name="activate"),
    re_path(
        r"^activate/retry/(?P<activation_key>\w+)/$",
        views.activate,
        name="activate_retry",
    ),
    re_path(r"^profile/(?P<username>[-\w]+)$", views.profile, name="profile"),
    re_path(
        r"^profile/(?P<username>[-\w]+)/edit-account$",
        views.account_edit,
        name="account_edit",
    ),
    re_path(
        r"^profile/(?P<username>[-\w]+)/edit-profile$",
        views.profile_edit,
        name="profile_edit",
    ),
    re_path(
        r"^profile/(?P<username>[-\w]+)/edit-settings$",
        views.settings_edit,
        name="user_settings_edit",
    ),
]

project/datacore/urls.py
from django.conf.urls import include
from django.urls import path, re_path
from rest_framework import routers

from . import api, views

app_name = "datacore"

router = routers.DefaultRouter()
router.register(r"data_sources", api.DataSourceViewSet)
router.register(r"references", api.ReferenceViewSet)
router.register(r"linguistics", api.ComponentViewSet)
router.register(r"languages", api.LanguageViewSet)
router.register(r"word_relation_types", api.WordRelationTypeViewSet)
router.register(r"word_relation", api.WordRelationViewSet)
router.register(r"words", api.WordViewSet)
router.register(r"named_entities", api.NamedEntityViewSet)
router.register(r"word_collections", api.WordCollectionViewSet)
router.register(r"concepts", api.ConceptViewSet)
router.register(r"domain_ontologies", api.DomainOntologyViewSet)
router.register(r"definitions", api.DefinitionViewSet)
router.register(r"examples", api.ExampleViewSet)
router.register(r"relations", api.RelationViewSet)
router.register(r"attributes", api.AttributeViewSet)
router.register(r"properties", api.PropertyViewSet)
router.register(r"rules", api.RuleViewSet)
router.register(r"restrictions", api.RestrictionViewSet)
router.register(r"axioms", api.AxiomViewSet)
router.register(r"corpus", api.CorporaViewSet)
router.register(r"phrase_collection", api.PhraseCollectionViewSet)
router.register(r"documents", api.DocumentViewSet)
router.register(r"phrase_relation_types", api.PhraseRelationTypeViewSet)
router.register(r"phrases", api.PhraseViewSet)
router.register(r"templates", api.TemplateViewSet)


urlpatterns = [
    # home
    re_path(r"^$", views.index, name="home"),
    path("search/", views.search, name="search"),
    path("analyze/", views.analyze, name="analyze"),
    # API
    path(r"api/", include((router.urls, "datacore"))),
    # all the pages
    path("corpora/", views.corpora, name="corpora"),
    path("corpora/add/", views.corpora_add, name="corpora_add"),
    re_path(
        r"^corpus/(?P<id>\d+)/documents_add$",
        views.corpus_documents_add,
        name="corpus_documents_add",
    ),
    re_path(
        r"^corpus/(?P<id>\d+)/documents$",
        views.corpus_documents,
        name="corpus_documents",
    ),
    re_path(
        r"^corpus/(?P<id>\d+)/phrase_collections_add$",
        views.corpus_phrase_collections_add,
        name="corpus_phrase_collections_add",
    ),
    re_path(
        r"^corpus/(?P<id>\d+)/phrase_collections$",
        views.corpus_phrase_collections,
        name="corpus_phrase_collections",
    ),
    re_path(r"^corpus/(?P<id>\d+)/edit$", views.corpus_edit, name="corpus_edit"),
    re_path(r"^corpus/(?P<id>\d+)/delete$", views.corpus_delete, name="corpus_delete"),
    re_path(r"^corpus/(?P<id>\d+)/$", views.corpus, name="corpus"),
    path("documents/", views.documents, name="documents"),
    path("documents/add", views.documents_add, name="documents_add"),
    re_path(r"^document/(?P<id>\d+)/edit$", views.document_edit, name="document_edit"),
    re_path(
        r"^document/(?P<id>\d+)/delete$", views.document_delete, name="document_delete"
    ),
    re_path(r"^document/(?P<id>\d+)$", views.document, name="document"),
    path("phrase-collections/", views.phrase_collections, name="phrase_collections"),
    path(
        "phrase-collections/add",
        views.phrase_collections_add,
        name="phrase_collections_add",
    ),
    re_path(
        r"^phrase-collection/(?P<id>\d+)/add_phrase$",
        views.phrase_collection_add_phrase,
        name="phrase_collection_add_phrase",
    ),
    re_path(
        r"^phrase-collection/(?P<id>\d+)/edit$",
        views.phrase_collection_edit,
        name="phrase_collection_edit",
    ),
    re_path(
        r"^phrase-collection/(?P<id>\d+)/delete$",
        views.phrase_collection_delete,
        name="phrase_collection_delete",
    ),
    re_path(
        r"^phrase-collection/(?P<id>\d+)$",
        views.phrase_collection,
        name="phrase_collection",
    ),
    path("phrases/", views.phrases, name="phrases"),
    path("phrases/add", views.phrases_add, name="phrases_add"),
    re_path(r"^phrase/(?P<id>\d+)/edit$", views.phrase_edit, name="phrase_edit"),
    re_path(r"^phrase/(?P<id>\d+)/delete$", views.phrase_delete, name="phrase_delete"),
    re_path(r"^phrase/(?P<id>\d+)$", views.phrase, name="phrase"),
    path("words/", views.words, name="words"),
    path("words/add", views.words_add, name="words_add"),
    re_path(r"^word/(?P<id>\d+)/edit$", views.word_edit, name="word_edit"),
    re_path(r"^word/(?P<id>\d+)/delete$", views.word_delete, name="word_delete"),
    re_path(r"^word/(?P<id>\d+)$", views.word, name="word"),
    path("domain_ontologies/", views.domain_ontologies, name="domain_ontologies"),
    path(
        "domain_ontologies/add",
        views.domain_ontologies_add,
        name="domain_ontologies_add",
    ),
    re_path(
        r"^domain_ontology/(?P<id>\d+)/concept_add$",
        views.domain_ontology_concept_add,
        name="domain_ontology_concept_add",
    ),
    re_path(
        r"^domain_ontology/(?P<id>\d+)/edit$",
        views.domain_ontology_edit,
        name="domain_ontology_edit",
    ),
    re_path(
        r"^domain_ontology/(?P<id>\d+)/delete$",
        views.domain_ontology_delete,
        name="domain_ontology_delete",
    ),
    re_path(
        r"^domain_ontology/(?P<id>\d+)$", views.domain_ontology, name="domain_ontology"
    ),
    path("concepts/", views.concepts, name="concepts"),
    path("concepts/add", views.concepts_add, name="concepts_add"),
    re_path(
        r"^concept/(?P<id>\d+)/synonyms$",
        views.concept_synonyms,
        name="concept_synonyms",
    ),
    re_path(
        r"^concept/(?P<id>\d+)/synonyms_add$",
        views.concept_synonyms_add,
        name="concept_synonyms_add",
    ),
    re_path(
        r"^concept/(?P<id>\d+)/synonym_edit/(?P<rel_id>\d+)$",
        views.concept_synonym_edit,
        name="concept_synonym_edit",
    ),
    re_path(
        r"^concept/(?P<id>\d+)/antonyms$",
        views.concept_antonyms,
        name="concept_antonyms",
    ),
    re_path(
        r"^concept/(?P<id>\d+)/antonyms_add$",
        views.concept_antonyms_add,
        name="concept_antonyms_add",
    ),
    re_path(
        r"^concept/(?P<id>\d+)/antonym_edit/(?P<rel_id>\d+)$",
        views.concept_antonym_edit,
        name="concept_antonym_edit",
    ),
    re_path(
        r"^concept/(?P<id>\d+)/definitions$",
        views.concept_definitions,
        name="concept_definitions",
    ),
    re_path(
        r"^concept/(?P<id>\d+)/definitions_add$",
        views.concept_definitions_add,
        name="concept_definitions_add",
    ),
    re_path(
        r"^concept/(?P<id>\d+)/definition_edit/(?P<rel_id>\d+)$",
        views.concept_definition_edit,
        name="concept_definition_edit",
    ),
    re_path(
        r"^concept/(?P<id>\d+)/examples$",
        views.concept_examples,
        name="concept_examples",
    ),
    re_path(
        r"^concept/(?P<id>\d+)/examples_add$",
        views.concept_examples_add,
        name="concept_examples_add",
    ),
    re_path(
        r"^concept/(?P<id>\d+)/example_edit/(?P<rel_id>\d+)$",
        views.concept_example_edit,
        name="concept_example_edit",
    ),
    re_path(
        r"^concept/(?P<id>\d+)/relationships$",
        views.concept_relationships,
        name="concept_relationships",
    ),
    re_path(
        r"^concept/(?P<id>\d+)/relationships_add$",
        views.concept_relationships_add,
        name="concept_relationships_add",
    ),
    re_path(
        r"^concept/(?P<id>\d+)/visualization$",
        views.concept_visualization,
        name="concept_visualization",
    ),
    re_path(r"^concept/(?P<id>\d+)$", views.concept, name="concept"),
    path("entities/", views.entities, name="entities"),
    path("entities/add", views.entities_add, name="entities_add"),
    re_path(r"^entity/(?P<id>\d+)/edit$", views.entity_edit, name="entity_edit"),
    re_path(r"^entity/(?P<id>\d+)/delete$", views.entity_delete, name="entity_delete"),
    re_path(r"^entity/(?P<id>\d+)$", views.entity, name="entity"),
    path("templates/", views.templates, name="templates"),
    re_path(r"^template/(?P<id>\d+)$", views.template, name="template"),
    path("components/", views.components, name="components"),
    re_path(r"^component/(?P<slug>.+)/$", views.component, name="component"),
    path("languages/", views.languages, name="languages"),
    path("languages/add", views.languages_add, name="languages_add"),
    re_path(r"^language/(?P<id>\d+)/edit$", views.language_edit, name="language_edit"),
    re_path(
        r"^language/(?P<id>\d+)/delete$", views.language_delete, name="language_delete"
    ),
    re_path(r"^language/(?P<id>\d+)/$", views.language, name="language"),
    path("word-relation-types/", views.word_relation_types, name="word_relation_types"),
    path(
        "word-relation-types/add",
        views.word_relation_types_add,
        name="word_relation_types_add",
    ),
    re_path(
        r"^word-relation-type/(?P<id>\d+)/edit$",
        views.word_relation_type_edit,
        name="word_relation_type_edit",
    ),
    re_path(
        r"^word-relation-type/(?P<id>\d+)/delete$",
        views.word_relation_type_delete,
        name="word_relation_type_delete",
    ),
    re_path(
        r"^word-relation-type/(?P<id>\d+)$",
        views.word_relation_type,
        name="word_relation_type",
    ),
    path("word-relations/", views.word_relations, name="word_relations"),
    path("word-relations/add", views.word_relations_add, name="word_relations_add"),
    re_path(
        r"^word-relation/(?P<id>\d+)/edit$",
        views.word_relation_edit,
        name="word_relation_edit",
    ),
    re_path(
        r"^word-relation/(?P<id>\d+)/delete$",
        views.word_relation_delete,
        name="word_relation_delete",
    ),
    re_path(r"^word-relation/(?P<id>\d+)$", views.word_relation, name="word_relation"),

project/account/templates/activate_fail.html
{% extends base_template %}
{% load static %}
{% load thumbnail %}
{% load i18n %}

{% block title %}{% trans "Account activation failed." %}{% endblock %}
{% block content_title %}<h2>{% trans "Your account could not be activated..." %}</h2>{% endblock %}

{% block content %}
<main class="container activation-page">
	<p>{% trans "Your account could not be activated. This could be because your activation link has aged." %}</p>
	<p>{% trans "Please try signing up again or contact us if you think something went wrong." %}</p>
</main>
{% endblock %}

project/account/templates/activate_retry.html
{% extends "base-clean-header.html" %}
{% load static %}
{% load thumbnail %}
{% load i18n %}

{% block title %}{% trans "Account activation failed." %}{% endblock %}
{% block content_title %}<h2>{% trans "Your account could not be activated..." %}</h2>{% endblock %}

{% block content %}
<main class="container activation-page">
	<p>{% trans "Your account could not be activated because activation link is expired." %}</p>
	<p><a href="{% url 'activate_retry' activation_key %}">{% trans "Request a new activation link." %}</a></p>
</main>
{% endblock %}

project/account/templates/activate_retry_success.html
{% extends "base-clean-header.html" %}
{% load static %}
{% load thumbnail %}
{% load i18n %}

{% block title %}{% trans "Account re-activation succeeded." %}{% endblock %}
{% block content_title %}<h2>{% trans "Account re-activation" %}</h2>{% endblock %}

{% block content %}
<main class="container activation-page">
	<p>{% blocktrans %}You requested a new activation of your account..{% endblocktrans %}</p>
	<p>{% blocktrans %}You have been sent an e-mail with an activation link to the supplied email.{% endblocktrans %}</p>
</main>
{% endblock %}

project/account/templates/profile-account-edit.html
{% extends base_template %}
{% load static %}
{% load thumbnail %}
{% load widget_tweaks %}
{% load i18n %}

{% block title %}{% trans "Edit Account" %}{% endblock %}

{% block content %}
<main class="container profile">
	<div class="row">
		<div class="col-md-3 profile-sidebar-container">
			{% include "profile-sidebar.html" %}
		</div>
		<div class="col-md-9">
			<div class="row profile-body">
				<div class="content clearfix">
					<form action="" enctype="multipart/form-data" method="post">
						{% csrf_token %}
						{% include 'modal-form.html' %}
						<input class="btn btn-primary pull-right" value="{% trans 'Save changes' %}" type="submit">
					</form>
				</div>
			</div>
		</div>
	</div>
</main>
{% endblock %}

project/account/templates/profile-edit.html
{% extends base_template %}
{% load static %}
{% load thumbnail %}
{% load widget_tweaks %}
{% load i18n %}

{% block title %}{% trans "Edit Profile" %}{% endblock %}

{% block content %}
	<main class="container profile">
		<div class="row">
			<div class="col-md-3 profile-sidebar-container">
				{% include "profile-sidebar.html" %}
			</div>
			<div class="col-md-9">
				<div class="row profile-body">
					<div class="content clearfix">
						<form action="" enctype="multipart/form-data" method="post">
							{% csrf_token %}
							{% include 'modal-form.html' %}
							<input class="btn btn-primary pull-right" value="{% trans 'Save changes' %}" type="submit">
						</form>
					</div>
				</div>
			</div>
		</div>
	</main>
{% endblock %}

project/account/templates/profile-list.html
{% extends base_template %}
{% load thumbnail %}
{% load static %}
{% load i18n %}

{% block content %}
<ul id="profile_list">
  {% for profile in profile_list %}
  <li>
  <a href="{% url 'profile' profile.user.username %}"><img src="{{ profile.get_mugshot_url }}" /></a>
  <a href="{% url 'profile' profile.user.username %}">{{ profile.user.username }}</a>
  </li>
  {% endfor %}
</ul>

{% if is_paginated %}
<div class="pagination">
  <span class="step-links">
	{% if page_obj.has_previous %}
	<a href="{% url 'profile_list_paginated' page_obj.previous_page_number %}">{% trans 'previous' %}</a>
	{% endif %}

	<span class="current">
	  {% blocktrans with page_obj.number as page and page_obj.paginator.num_pages as num_pages %}
	  Page {{ page }} of {{ num_pages }}
	  {% endblocktrans %}
	</span>

	{% if page_obj.has_next %}
	<a href="{% url 'profile_list_paginated'  page_obj.next_page_number %}">{% trans 'next' %}</a>
	{% endif %}
  </span>
</div>
{% endif %}

{% endblock %}

project/account/templates/profile-no-permission.html
{% extends "base-clean-header.html" %}
{% load static %}
{% load thumbnail %}
{% load i18n %}

{% block header %}
<link href="{% static 'css/profile.css' %}" rel="stylesheet">
{% endblock %}

{% block title %}{% trans "Edit Profile" %}{% endblock %}

{% block content %}
<main class="container-box">
	<div class="content clearfix">
		<h2 class="text-capitalize">
			Private Profile
		</h2>
		<p>Sorry, this profile is made private by it's owner. you can't view it.
		</p>
	</div>
</main>
{% endblock %}

project/account/templates/profile-private.html
{% extends base_template %}
{% load static %}
{% load thumbnail %}
{% load i18n %}

{% block header %}
<link href="{% static 'css/profile.css' %}" rel="stylesheet">
{% endblock %}

{% block title %}{% trans "Edit Profile" %}{% endblock %}

{% block content %}
<main class="container-box">
	<div class="content clearfix">
		<h2 class="text-capitalize">
			Private Profile
		</h2>
		<p>Sorry, this profile is made private by it's owner. you can't view it.
		</p>
	</div>
</main>
{% endblock %}

project/account/templates/profile-settings-edit.html
{% extends base_template %}
{% load static %}
{% load thumbnail %}
{% load widget_tweaks %}
{% load i18n %}


{% block title %}{% trans "Edit Account" %}{% endblock %}

{% block content %}
<main class="container profile">
	<div class="row">
		<div class="col-md-3 profile-sidebar-container">
			{% include "profile-sidebar.html" %}
		</div>
		<div class="col-md-9">
			<div class="row profile-body">
				<div class="content clearfix">
					<form action="" enctype="multipart/form-data" method="post">
						{% csrf_token %}
						{% include 'modal-form.html' %}
						<input class="btn btn-primary pull-right" value="{% trans 'Save changes' %}" type="submit">
					</form>
				</div>
			</div>
		</div>
	</div>
</main>
{% endblock %}

project/account/templates/profile-sidebar.html
{% load thumbnail %}
{% load static %}

<link href="{% static 'css/profile.css' %}" rel="stylesheet">
<div class="profile-sidebar">
	{% thumbnail profile.avatar "256x256" crop="center" as im %}
	<img src="{{ im.url }}" class="rounded-circle profile-avatar" width="{{ im.width }}" height="{{ im.height }}">
	{% endthumbnail %}
	<div class="profile-name">
		{% if profile.user.get_full_name %}
		<h2 class="text-capitalize">
			{{ profile.user.get_full_name }}
		</h2>
		<h4 class="text-lowercase"><a href="{% url 'account:profile' user.username %}">@{{ profile.user.username }}</a></h4>
		{% else %}
		<h4 class="text-lowercase"><a href="{% url 'account:profile' user.username %}">@{{ profile.user.username }}</a></h4>
		{% endif %}
		<ul hx-swap="innerHTML show:window:top" hx-target="#main-container" hx-push-url="true" hx-boost="true" hx-indicator="#navbar-indicator"  class="profile-usermenu">
			<li class="{% if 'edit-profile' not in request.path and 'edit-account' not in request.path and 'edit-settings' not in request.path %}active{% endif %}">
				<a href="{% url 'account:profile' user.username %}"><i class="fa fa-user"></i>Profile</a>
			</li>
			{% if request.user.is_superuser or request.user.username == username %}
				<li class="{% if 'edit-profile' in request.path %}active{% endif %}">
					<a href="{% url 'account:profile_edit' user.username %}"><i class="fa fa-magic"></i>Edit Profile</a>
				</li>
				<li class="{% if 'edit-account' in request.path %}active{% endif %}">
					<a href="{% url 'account:account_edit' user.username %}"><i class="fa fa-pencil-square-o"></i>Edit Account</a>
				</li>
				<li class="{% if 'edit-settings' in request.path %}active{% endif %}">
					<a href="{% url 'account:user_settings_edit' user.username %}"><i class="fa fa-wrench"></i>Account Settings</a>
				</li>
			{% endif %}
		</ul>
	</div>
</div>

project/account/templates/profile.html
{% extends base_template %}
{% load static %}
{% load i18n %}

{% block title %}{{ profile.user.username }} - {% trans "Profile" %}{% endblock %}

{% block content %}
<main class="container profile">
	<div class="row">
		<div class="col-md-3 profile-sidebar-container">
			{% include "profile-sidebar.html" %}
		</div>
		<div class="col-md-9">
			<div class="row profile-body">
				<div class="profile-fields">
					{% if profile.bio %}
					<div class="profile-bio">
						{{ profile.bio|linebreaks }}
					</div>
					{% endif %}
					{% if profile.location %}
					<div class="profile-location">
						<i class="fa fa-map-marker"></i>
						{{ profile.location }}
					</div>
					{% endif %}
					{% if profile.website %}
					<div class="profile-location">
						<i class="fa fa-external-link-square"></i>
						{{ profile.website|urlize }}
					</div>
					{% endif %}
					{% if profile.public_mail %}
					<div class="profile-public-mail">
						<i class="fa fa-envelope"></i>
						{{ profile.public_mail }}
					</div>
					{% endif %}
				</div>
			</div>
		</div>
	</div>
</main>
{% endblock %}

project/account/templates/signin-form.html
{% extends base_template %}
{% load static %}
{% load thumbnail %}
{% load widget_tweaks %}
{% load i18n %}

{% block title %}{% trans "Login" %}{% endblock %}

{% block content %}
<form action="{{ url }}" method="post">
	{% csrf_token %}
	<div class="text-center">
		<h3><a class="navbar-brand" href="{% url 'datacore:home' %}">{% block title %}ElevateNLP{% endblock %}</a></h3>
	</div>

	<div class="modal-header">
		<h1 class="modal-title fs-5" id="modal-label">{{ title }}</h1>
		{% if base_template != 'base.html' %}<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>{% endif %}
	</div>
	<div class="modal-body">
		{% include 'modal-form.html' %}
	</div>
	<div class="modal-footer gap-2">
		<div class="p-2 flex-fill">
			Don't have an account? <a hx-target="#user-modal-container" hx-push-url="false" hx-boost="true" hx-indicator="#navbar-indicator" href="{% url 'account:signup' %}">Create Account</a>
		</div>
		<input type="submit" value="SignIn" class="btn btn-lg btn-primary pull-right" />
	</div>
</form>
{% endblock %}

project/account/templates/signup-form.html
{% extends base_template %}
{% load static %}
{% load thumbnail %}
{% load widget_tweaks %}
{% load i18n %}


{% block title %}{% trans "SignUp" %}{% endblock %}

{% block content %}
<form action="{{ url }}" method="post">
	{% csrf_token %}
	<div class="text-center">
		<h3><a class="navbar-brand" href="{% url 'datacore:home' %}">{% block title %}ElevateNLP{% endblock %}</a></h3>
	</div>

	<div class="modal-header">
		<h1 class="modal-title fs-5" id="modal-label">{{ title }}</h1>
		{% if base_template != 'base.html' %}<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>{% endif %}
	</div>
	<div class="modal-body">
		{% include 'modal-form.html' %}
	</div>
	<div class="modal-footer gap-2">
		<div class="p-2 flex-fill">
			Already have an account? <a hx-target="#user-modal-container" hx-push-url="false" hx-boost="true" hx-indicator="#navbar-indicator" href="{% url 'account:signin' %}">Login</a>
		</div>
		<input type="submit" value="SignUp" class="btn btn-lg btn-primary pull-right" />
	</div>
</form>
{% endblock %}